name: Update README on Push

on:
  push:
    branches:
      - main

jobs:
  update-README:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git --version
          git config user.name "README bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
          architecture: x64

      - name: Update README
        run: |
          python .github/update_README.py
          git add README.md
          git commit -m "Auto-update README" || echo "No changes to commit"
          git push
